version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Adjust based on your Node.js version
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building the React app"
      - npm run build

  post_build:
    commands:
      - echo "Syncing build artifacts to S3"
      - aws s3 sync build/ s3://sessions-red-react-app-deployments/ --delete

artifacts:
  files:
    - '**/*'
  discard-paths: yes